# -*- coding: utf-8 -*-
"""data_extraction.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13nVh-LkfcBwafDSeQQ-gQf8rRTl6Ci7z
"""

!pip install pymupdf pandas

import fitz  # PyMuPDF
import pandas as pd

import re

def extract_features(pdf_file):
    # Open the PDF file
    pdf_document = fitz.open(pdf_file)

    # Initialize variables for features
    num_pages = len(pdf_document)
    token_count = 0
    word_count = 0
    sentence_count = 0
    text = ''

    # Extract text and calculate features
    for page_number in range(num_pages):
        page = pdf_document[page_number]
        text += page.get_text()

        # Tokenization
        tokens = re.findall(r'\b\w+\b', page.get_text())
        token_count += len(tokens)

        word_count += len(page.get_text().split())
        sentence_count += len(page.get_text().split('.'))

    pdf_document.close()

    # Create a dictionary to store features
    pdf_features = {
        'PDF File': pdf_file,
        'Number of Pages': num_pages,
        'Token Count': token_count,
        'Word Count': word_count,
        'Sentence Count': sentence_count,
        'Text': text
    }

    return pdf_features


def create_csv(pdf_files, output_csv):
    # Initialize an empty list to store features for all PDFs
    all_features = []

    # Extract features for each PDF file
    for pdf_file in pdf_files:
        features = extract_features(pdf_file)
        all_features.append(features)

    # Convert the list of dictionaries to a pandas DataFrame
    df = pd.DataFrame(all_features)

    # Save DataFrame to a CSV file
    df.to_csv(output_csv, index=False)

    return df

Foundation_Foods_Documentation_Apr2024='/content/Foundation_Foods_Documentation_Apr2024.pdf'
food_2='/content/food_2.pdf'
food_3='/content/food_3.pdf'
food_4='/content/food_4.pdf'
food='/content/food.pdf'
Composition_of_Foods='/content/Composition_of_Foods.pdf'

pdf_files = [Foundation_Foods_Documentation_Apr2024,food_2,food_3,food_4,food,Composition_of_Foods]
output_csv = 'csv_output.csv'

create_csv(pdf_files, output_csv)

